name: Weave Scope
description: "Monitoring, visualisation and management for Docker"
<<<<<<< HEAD
version: 0.12.0
=======
version: 1.0.0
>>>>>>> rancher/master
category: Monitoring
maintainer: "Ilya Dmitrichenko <ilya@weave.works>"
license: "Apache License v2.0"
