name: px-dev
description: |
  Software defined enterprise storage for Linux Containers.
<<<<<<< HEAD
version: 1.0.2-2016-09-07-GA
=======
version: 1.0.6-2016-10-05-GA
>>>>>>> rancher/master
category: Storage
