name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster
<<<<<<< HEAD
version: 3.4.8-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
license: 
=======
version: 3.4.9-rancher1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
license: 
>>>>>>> rancher/master
