db:
    image: mysql:5.7
    labels:
        io.rancher.sidekicks: dbConfig
    environment:
        MYSQL_ROOT_PASSWORD: password
        MYSQL_DATABASE: edxapp
        MYSQL_USER: edxapp001
        MYSQL_PASSWORD: password
    volumes:
     - ${EDX_MYSQL_DATA_ROOT}:/var/lib/mysql
    volume_driver: ${volume_driver}
    
dbConfig:
    image: mysql:5.7
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    command: |
      bash -c "sleep 2m; mysql -uroot -ppassword -h db -e \"create database edxapp_csmh;\""

mongo:
    labels:
        io.rancher.sidekicks: mongoConfig
    image: mongo:3.3
    volumes:
     - ${EDX_MONGO_DATA_ROOT}:/data/db
    volume_driver: ${volume_driver}

mongoConfig:
    image: mongo:3.3
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    command: |
      bash -c "sleep 2m; echo 'db.createUser({ user: \"edxapp\", pwd: \"password\", roles: [ { role: \"readWrite\", db: \"edxapp\" } ] });' > createEdxappUser.js; mongo mongo/edxapp createEdxappUser.js; echo 'db.createUser({ user: \"cs_comments_service\", pwd: \"password\", roles: [ { role: \"readWrite\", db: \"cs_comments_service\" } ] });' > createForumUser.js; mongo mongo/cs_comments_service createForumUser.js"
    
# Need to build our own for ES 0.9
es:
    image: opensaas/edx-elasticsearch
    volumes:
     - ${EDX_ES_DATA_ROOT}:/data
    volume_driver: ${volume_driver}

memcache:
    image: memcached:1.4.24
    volumes:
     - ${EDX_MEMCACHE_DATA_ROOT}:/data
    volume_driver: ${volume_driver}


rabbitmq:
    image: rabbitmq:3.5.3
    volumes:
     - ${EDX_RABBIT_DATA_ROOT}:/var/lib/rabbitmq
    volume_driver: ${volume_driver}
    environment:
        RABBITMQ_DEFAULT_USER: celery
        RABBITMQ_DEFAULT_PASS: celery

forums:
    image: opensaas/edx-forums
    labels:
        io.rancher.container.pull_image: always
    volumes:
     - ${EDXAPP_CS_COMMENTS_ROOT}:/edx/app/forum/cs_comments_service
    volume_driver: ${volume_driver}
   

lms:
    labels:
        io.rancher.container.pull_image: always
    image: opensaas/edxapp:trusty-v3
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp/edx-platform
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}
    command: |
        bash -c "rm -rf /edx/app/edx_ansible/edx_ansible; git clone https://github.com/OpenSaasAU/edx-configuration /edx/app/edx_ansible/edx_ansible; cd /edx/app/edx_ansible/edx_ansible/docker/plays; rm -f /edx/app/supervisor/conf.d/*; /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook edxapp.yml -i '127.0.0.1,' -c local -e \"service_type='lms' EDXAPP_PLATFORM_NAME='${EDXAPP_PLATFORM_NAME}' EDXAPP_SITE_NAME='${EDX_DOMAIN_NAME}' EDXAPP_CMS_SITE_NAME='${STUDIO_DOMAIN_NAME}'\" -t 'install:app-requirements,install:base,install:configuration' -e@/edx/app/edx_ansible/edx_ansible/docker/build/edxapp/rancher_overrides.yml; /edx/app/supervisor/venvs/supervisor/bin/supervisord -n --configuration /edx/app/supervisor/supervisord.conf"
    
cms:
    labels:
        io.rancher.container.pull_image: always
    image: opensaas/edxapp:trusty-v3
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp/edx-platform
     - /dev/log:/dev/log
    volume_driver: ${volume_driver}
    command: |
        bash -c "rm -rf /edx/app/edx_ansible/edx_ansible; git clone https://github.com/OpenSaasAU/edx-configuration /edx/app/edx_ansible/edx_ansible; cd /edx/app/edx_ansible/edx_ansible/docker/plays; rm -f /edx/app/supervisor/conf.d/*; /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook edxapp.yml -i '127.0.0.1,' -c local -e \"service_type='cms' EDXAPP_PLATFORM_NAME='${EDXAPP_PLATFORM_NAME}' EDXAPP_SITE_NAME='${EDX_DOMAIN_NAME}' EDXAPP_CMS_SITE_NAME='${STUDIO_DOMAIN_NAME}'\" -t 'install:app-requirements,install:base,install:configuration' -e@/edx/app/edx_ansible/edx_ansible/docker/build/edxapp/rancher_overrides.yml; /edx/app/supervisor/venvs/supervisor/bin/supervisord -n --configuration /edx/app/supervisor/supervisord.conf"

edxappMigrate:
    image: opensaas/edxapp:trusty-v3
    volumes:
     - ${EDXAPP_PLATFORM_ROOT}:/edx/app/edxapp/edx-platform
     - /dev/log:/dev/log
     - ${EDXAPP_STATICFILES_ROOT}:/edx/var/edxapp/staticfiles
    labels:
        io.rancher.container.hostname_override: container_name
        io.rancher.container.start_once: true
    volume_driver: ${volume_driver}
    command: |
        bash -c "sleep 5m; rm -rf /edx/app/edx_ansible/edx_ansible; git clone https://github.com/OpenSaasAU/edx-configuration /edx/app/edx_ansible/edx_ansible; cd /edx/app/edx_ansible/edx_ansible/docker/plays; /edx/app/edx_ansible/venvs/edx_ansible/bin/ansible-playbook edxapp.yml -i '127.0.0.1,' -c local -e \"migrate_db='yes' COMMON_MYSQL_MIGRATE_USER='root'\" -t 'install:configuration,install:app-requirements,install:code,gather_static_assets,migrate' -e@/edx/app/edx_ansible/edx_ansible/docker/build/edxapp/ansible_overrides.yml"
        
nginx:
    image: nginx
    volumes:
     - ${EDXAPP_STATICFILES_ROOT}:/usr/share/nginx/html
    volume_driver: ${volume_driver}
    
lb:
    ports:
     - 80:80
    labels:
        io.rancher.loadbalancer.target.nginx: preview.${EDX_DOMAIN_NAME}:80/static=80,${EDX_DOMAIN_NAME}:80/static=80,${STUDIO_DOMAIN_NAME}:80/static=80
        io.rancher.scheduler.global: 'true'
        io.rancher.loadbalancer.target.lms: ${EDX_DOMAIN_NAME}:80=8000,preview.${EDX_DOMAIN_NAME}:80=8000
        io.rancher.loadbalancer.target.cms: ${STUDIO_DOMAIN_NAME}:80=8010
    tty: true
    links:
     - nginx:nginx
     - cms:cms
     - lms:lms
    image: rancher/load-balancer-service
    stdin_open: true