name: Apache Zookeeper
description: |
  (Experimental) Zookeeper cluster
<<<<<<< HEAD
version: 3.4.8-k8s1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
=======
version: 3.4.9-k8s1
category: Clustering
maintainer: "Raul Sanchez <rawmind@gmail.com>"
projectURL: https://github.com/rawmind0/alpine-zk
>>>>>>> rancher/master
