portworx:
  labels:
    io.rancher.container.create_agent: 'true'
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: 'always'
  image: portworx/px-dev
  container_name: px
  ipc: host
  net: host
  privileged: true
  environment:
<<<<<<< HEAD
    CLUSTER_TOKEN: ${cluster_token}
=======
    CLUSTER_ID: ${cluster_id}
    KVDB: ${kvdb}
>>>>>>> rancher/master
  volumes:
     - /dev:/dev
     - /usr/src:/usr/src
     - /run/docker/plugins:/run/docker/plugins
     - /var/lib/osd:/var/lib/osd:shared
     - /etc/pwx:/etc/pwx
     - /opt/pwx/bin:/export_bin:shared
     - /var/run/docker.sock:/var/run/docker.sock
     - /var/cores:/var/cores
<<<<<<< HEAD
  command: -t ${cluster_token} -a -f
=======
  command: -c ${cluster_id} -k ${kvdb} -a -z -f
>>>>>>> rancher/master
